version: '2.1'

services:
  integration:
    build:
      context: './integration'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
  backend:
    build:
      context: './backend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
  frontend:
    build:
      context: './frontend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
