version: '2.1'

services:
  backend:
    build:
      context: '.'
      dockerfile: './backend/Dockerfile.template'
    privileged: 'true'
    ports:
      - "201:22"
  frontend:
    build:
      context: '.'
      dockerfile: './frontend/Dockerfile.template'
    privileged: 'true'
    ports:
      - "80:8080"
      - "443:443"
      - "5000:5000"
      - "8080:8080"
      - "202:22"
