version: '2.1'

volume:
  data:

services:
  backend:
    build:
      context: '.'
      dockerfile: './backend/Dockerfile'
    privileged: 'true'
    ports:
      - "201:22"
    volume:
      - data:/data

  frontend:
    build:
      context: '.'
      dockerfile: './frontend/Dockerfile'
    privileged: 'true'
    ports:
      - "80:8080"
      - "443:443"
      - "5000:5000"
      - "8080:8080"
      - "202:22"
    volume:
      - data:/data
