version: '2.1'

volumes:
  data:

services:
  backend:
    build:
      context: '.'
      dockerfile: './backend/Dockerfile'
    privileged: 'true'
    ports:
      - "201:22"
      - "3000:3000"
    volumes:
      - data:/data

  frontend:
    build:
      context: '.'
      dockerfile: './frontend/Dockerfile'
    privileged: 'true'
    ports:
      - "80:8080"
      - "443:443"
      - "5000:5000"
      - "8080:8080"
      - "202:22"
    volumes:
      - data:/data
    restart: always