version: '2.1'

volumes:
  ssh:

services:
  integration:
    build:
      context: '.'
      dockerfile: './integration/Dockerfile.template'
    privileged: 'true'
  backend:
    build:
      context: './backend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
  frontend:
    build:
      context: './frontend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
