version: '2.1'

volumes:
  ssh:

services:
  integration:
    build:
      context: '.'
      dockerfile: './integration/Dockerfile.template'
    privileged: 'true'
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
        SSH_AUTH_SOCK: /ssh-agent
  backend:
    build:
      context: './backend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
  frontend:
    build:
      context: './frontend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
