version: '2.1'

services:
  backend:
    build:
      context: './backend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
  frontend:
    build:
      context: './frontend'
      dockerfile: './Dockerfile.template'
    privileged: 'true'
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
      - "8080:8080"
